name       : adios2
version    : 2.7.1
release    : 2
source     :
    - https://github.com/ornladios/ADIOS2/archive/refs/tags/v2.7.1.tar.gz : c8e237fd51f49d8a62a0660db12b72ea5067512aa7970f3fcf80b70e3f87ca3e
homepage   : https://github.com/ornladios/ADIOS2
license    : Apache-2.0
component  : programming.library
summary    : Adaptable Input Output System version 2
description: |
    It is a framework for scientific data I/O to publish and subscribe to data when and where required.

    ADIOS2 transports data as groups of self-describing variables and attributes across different media types (such as files, wide-area-networks, and remote direct memory access) using a common application programming interface for all transport modes. ADIOS2 can be used on supercomputers, cloud systems, and personal computers.
libsplit   : no
builddeps  :
    - pkgconfig(blosc)
    - pkgconfig(hdf5)
    - pkgconfig(libfabric)
    - pkgconfig(libpng)
    - pkgconfig(libzmq)
    - pkgconfig(mgard)
    - pkgconfig(pugixml)
    - pkgconfig(sz)
    - pkgconfig(yaml-cpp)
    - bzip2-devel
    - nlohmann-json
    - pybind11
    - zfp-devel
setup      : |
    %patch -p1 < $pkgfiles/include-memory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
